app:
  version : '@project.version@'

server:
  port: 8086
  servlet:
    context-path: /student

spring:
  datasource:
    #          url:  jdbc:mysql://dropone-mariadb.cunylfqdsouy.ap-south-1.rds.amazonaws.com:3306/wella_products?useSSL=false
    #          username: admin
    #          password: Admin$123
    #url : jdbc:mysql://ec2-13-232-46-155.ap-south-1.compute.amazonaws.com:3306/wella_products?useSSL=false
    ##username : admin
    #password : adminadmin
    url: jdbc:mysql://localhost:3306/rec_student?autoReconnect=true
    username: root
    password: root
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate
      #ddl-auto: create
      generate-ddl: true




timeZone: "Asia/Kolkata"

passwordResetMail:
  body: 'To complete the password reset process, please click here: '

configKeys:
  versionKey: 'MINIMUM_REQUIRED_VERSION'

